name: zenbil_consumer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_links: 3.4.1
  app_links_platform_interface: 1.1.0
  assets_audio_player: 3.1.1
  assets_audio_player_web: 3.1.1
  auto_size_text: 3.0.0
  blurhash_dart: 1.2.1
  cached_network_image: 3.3.1
  carousel_slider: 4.2.1
  chewie: 1.8.1
  cloud_firestore:
  collection: 1.18.0
  devicelocale:
  dropdown_button2: 2.3.9
  easy_debounce: 2.0.1
  equatable: 2.0.5
  expandable: 5.0.1
  file_picker: 8.0.3
  firebase_analytics: 10.10.5
  firebase_analytics_platform_interface: 3.10.6
  firebase_analytics_web: 0.5.7+5
  firebase_auth:
  firebase_core: 2.31.0
  firebase_core_platform_interface: 5.0.0
  firebase_core_web: 2.17.0
  firebase_crashlytics: 3.5.5
  firebase_crashlytics_platform_interface: 3.6.33
  firebase_performance: 0.9.4+5
  firebase_performance_platform_interface: 0.1.4+33
  firebase_performance_web: 0.1.6+5
  flutter_animate: 4.5.0
  flutter_branch_sdk:
  flutter_cache_manager: 3.3.1
  flutter_google_places: 
    git:
      url: https://github.com/ShehanYjoz/flutter_google_places.git
  flutter_html: 3.0.0-beta.2
  flutter_native_splash: 2.3.1
  flutter_plugin_android_lifecycle: 2.0.20
  flutter_rating_bar: 4.0.1
  flutter_staggered_grid_view: 0.7.0
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  functions_client: 1.3.2
  geolocator: 12.0.0
  geolocator_android: 4.6.0
  geolocator_apple: 2.3.7
  geolocator_platform_interface: 4.2.3
  geolocator_web: 4.0.0
  go_router: 12.1.3
  google_fonts: 6.1.0
  google_maps: 7.1.0
  google_maps_flutter: 2.6.1
  google_maps_flutter_android: 2.8.1
  google_maps_flutter_ios: 2.6.1
  google_maps_flutter_platform_interface: 2.7.1
  google_maps_flutter_web: 0.5.7
  gotrue: 1.12.6
  hive: 2.2.3
  http: 1.2.1
  image: 4.0.17
  image_picker: 1.0.4
  image_picker_android: 0.8.8
  image_picker_for_web: 3.0.1
  image_picker_ios: 0.8.8+2
  image_picker_platform_interface: 2.9.1
  intl: 0.19.0
  json_path: 0.7.2
  mime_type: 1.0.0
  onesignal_flutter:
  package_info_plus: 8.0.0
  package_info_plus_platform_interface: 3.0.0
  page_transition: 2.1.0
  path_provider: 2.1.3
  path_provider_android: 2.2.5
  path_provider_foundation: 2.4.0
  path_provider_platform_interface: 2.1.2
  percent_indicator: 4.2.2
  photo_view: 0.14.0
  pin_code_fields: 8.0.1
  plugin_platform_interface: 2.1.8
  postgrest: 1.5.2
  provider: 6.1.2
  realtime_client: 1.4.0
  rxdart: 0.27.7
  share_plus: 9.0.0
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sign_in_with_apple: 4.3.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  smooth_page_indicator: 1.1.0
  sqflite: 2.2.6
  sticky_headers: 0.3.0+2
  storage_client: 1.5.4
  styled_divider: 1.0.4
  supabase: 1.11.11
  supabase_flutter: 1.10.24
  timeago: 3.6.1
  translator:
  universal_io: 2.2.2
  url_launcher: ^6.2.5
  url_launcher_android: 6.3.4
  url_launcher_ios: 6.3.1
  url_launcher_platform_interface: 2.3.2
  video_player: 2.8.6
  video_player_android: 2.4.16
  video_player_avfoundation: 2.6.1
  video_player_platform_interface: 6.2.2
  video_player_web: 2.3.1
  webview_flutter: 4.7.0
  webview_flutter_android: 3.15.0
  webview_flutter_platform_interface: 2.10.0
  webview_flutter_wkwebview: 3.12.0
  xml: 6.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.2.1
  package_info_plus: 8.0.0
  package_info_plus_platform_interface: 3.0.0
  rxdart: 0.27.7
  uuid: ^4.0.0
  win32: 5.5.1

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'
  adaptive_icon_background: '#007cff'
  adaptive_icon_foreground: 'assets/images/adaptive_foreground_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/

  fonts:
    - family: 'Neometric'
      fonts:
        - asset: assets/fonts/Neometric_Black_(Regular).otf
        - asset: assets/fonts/Neometric_Extra_Bold_(Bold).otf
          weight: 800

    - family: TablerIcons
      fonts:
        - asset: assets/fonts/Tabler-Icons.ttf
    - family: Emerald
      fonts:
        - asset: assets/fonts/Emerald.ttf
    - family: MagiconsRegular
      fonts:
        - asset: assets/fonts/MagiconsRegular.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

